# Generated by Django 5.2.7 on 2025-11-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="number",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
