# Generated by Django 5.2.7 on 2026-01-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_driver_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
