# Generated by Django 5.2.7 on 2026-01-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0003_alter_driver_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="headshot_url",
            field=models.CharField(blank=True, null=True),
        ),
    ]
