# Generated by Django 5.2.7 on 2026-01-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0002_race_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="raceresult",
            name="dnf",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
